server:
  port: 2332


mybatis-plus:
  mapper-locations: classpath:/mapper/main/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 查看日志

# mysql
spring:
  application:
    name: campusbox-main
  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
    #MySQL配置
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.33.233:10233/campusbox?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: compusbox
    password: compusbox

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8